module.exports.INCORRECT_DATA_ERROR_CODE = 400;
module.exports.NOT_FOUND_ERROR_CODE = 404;
module.exports.USER_EXISTS_ERROR_CODE = 409;
module.exports.UNAUTHORIZED_ERROR_CODE = 401;
module.exports.FORBIDDEN_DELETE_ERROR_CODE = 403;
module.exports.DEFAULT_ERROR_CODE = 500;
